AICoE/common

- .prow.yaml
> fix: s/master/main/ in Postsubmit CI

- github-config.yaml
Allow me to transfer repos and such... :angel: 
/assign @goern
> feat: Add tumido as admin

- github-config.yaml
Resolves: https://github.com/AICoE/common/issues/5
/assign @goern
> feat: Add suppathak

- .prow.yaml
Should also enable post sync jobs, since `run_if_changed` should be a regex.
> feat: Enable labels sync

- github-config.yaml
> feat: Add aakankshaduggal

- github-config.yaml
After repo transfer list this repo in the org config
/cc @hemajv 
/assign @goern
> feat: Add D^3 repo

- github-config.yaml
Sneak in a `meteor-operator` repository.
> feat: Add meteor operator

- github-config.yaml
Added mimotej (Michal Drla) to AICoE organization.
> feat: add mimotej to AICoE organization

- github-config.yaml
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
cc @codificat @goern
> Add codificat to members of AICoE and thoth station

- github-config.yaml
Signed-off-by: Christoph Görn <goern@redhat.com>
> a little rewording

- github-config.yaml
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
> Grant Thoth Station team write access on the tutorial repos

- github-config.yaml
Signed-off-by: Christoph Görn <goern@redhat.com>
> adding Maya

- github-config.yaml
Adding in:
Ryan Cook (cooktheryan)
Ricardo Noriega De Soto (oglok)
Frank Zdarsky (fzdarsky)
Huamin Chen (rootfs)
Luke Hinds (lukehinds)
Guy Margalit (guymguym)
> Adding octo team as users to common

- github-config.yaml
Create a repo for the Seraph project.
/cc @schwesig
> feat: Create a seraph project

- github-config.yaml
> Grant write perms on the donkeycar repo to the demo team

- github-config.yaml
This PR is a request to add myself, @MichaelClifford, to the list of admins for the AICoE org repos.
> Requesting admin status for the AICoE org

- github-config.yaml
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>
> Create Kafka2s3 repo for Data Hub team

- github-config.yaml
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>
> Clean up AICoE Members list

- github-config.yaml
Signed-off-by: Christoph Görn <goern@redhat.com>
> archive some repos

- github-config.yaml
Signed-off-by: Christoph Görn <goern@redhat.com>
> :arrow_up: adding a group for varangian contributors

- github-config.yaml
This PR is to add myself as a maintainer of the aicoe-ci and Thoth-related repos
> Move Pep to maintainer of Thoth and aicoe-ci repos

- github-config.yaml
The peribolos post-submit job after #58 merged failed to complete (full log below).
During its execution, it sent invitations to some old members, and it failed to update a few settings.
This PR removes these members from the configuration.
<details>
<summary>full log of last peribolos run</summary>
``` json
{
"client": "github",
"component": "peribolos",
"file": "k8s.io/test-infra/prow/github/client.go:917",
"func": "k8s.io/test-infra/prow/github.(*client).log",
"level": "info",
"msg": "Throttle(300, 100, *)",
"severity": "info",
"time": "2022-12-01T09:39:39Z"
}
{
"client": "github",
"component": "peribolos",
"file": "k8s.io/test-infra/prow/github/client.go:917",
"func": "k8s.io/test-infra/prow/github.(*client).log",
"level": "info",
"msg": "GetOrg(AICoE)",
"severity": "info",
"time": …
```
> Clean up github org members
